Hw2
kostikum/it-academy pull request #3
Opened 2019-02-25 08:13 UTC by kostikum

2019-02-25 19:14 UTC, tim-teacher requested changes

2019-02-25 19:14 UTC, tim-teacher commented on app/src/main/java/com/kostikum/itac/hw2/Hw2Activity.java
> +        allFlagsLinearLayout.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
Огого, это вы конечно круто завернули))), но представьте ситуацию с реальным проектам, вы же не будите каждый раз такое делать, к тому же это очень сложно поддерживать, если что то поменяется на дизайне нужно всегда помнить о том что нужно еще и код поменять.
То что вы эту штуку потыкали очень классно и хороший плюс для опыта. Но для решения конкретной проблемы это очень сложный код для такой простой задачи:) поэтому сделай те просто в xml.

2019-02-25 20:22 UTC, kostikum commented on app/src/main/java/com/kostikum/itac/hw2/Hw2Activity.java
> +        allFlagsLinearLayout.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
просто не удалось найти способ выдержать правильные пропорции флагов на разных устройствах для базовых разметок, насколько я понял только в КонстрэйнтЛэйауте такое есть

2019-02-26 10:59 UTC, tim-teacher approved these changes

2019-02-26 11:10 UTC, merged