Dz4
kostikum/it-academy pull request #6
Opened 2019-03-05 22:38 UTC by kostikum

2019-03-05 22:41 UTC, kostikum commented on app/src/main/java/com/kostikum/itac/dz4/ClockFragment.java
> +        mClockView.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
никак не могу придумать, как тут поместить сову без использования ВьюТриОбсервера
у нас в классе вью есть функция Math.min от ширины и высоты
на этот раз не нашел чем заменить это в XML и уместить сову в круг

2019-03-05 22:44 UTC, kostikum commented on app/src/main/AndroidManifest.xml
> +        android:name="com.kostikum.itac.ItacApplication"
насколько я понял, это обязательно, хотя в инструкции про это ни слова
иначе за основу будет взять другой экземпляр класса Application

2019-03-10 16:38 UTC, tim-teacher commented on app/src/main/java/com/kostikum/itac/dz4/ClockFragment.java
> +        mClockView.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
а зачем это нужно? вам же просто показать на экране и запустить анимацию.

2019-03-10 16:39 UTC, tim-teacher commented on app/src/main/AndroidManifest.xml
> +        android:name="com.kostikum.itac.ItacApplication"
если нужен доступ к классу апликейшен то да.

2019-03-10 16:43 UTC, tim-teacher requested changes

2019-03-10 16:43 UTC, tim-teacher commented on app/src/main/java/com/kostikum/itac/dz4/ClockFragment.java
> +    ClockView mClockView;
private

2019-03-10 16:43 UTC, tim-teacher commented on app/src/main/java/com/kostikum/itac/dz4/ClockView.java
> +    int mHours;
private

2019-03-10 16:43 UTC, tim-teacher commented on app/src/main/java/com/kostikum/itac/dz4/ClockView.java
> +
что за милион пробелом? )

2019-03-10 16:43 UTC, tim-teacher commented on app/src/main/java/com/kostikum/itac/dz4/PieChartView.java
> +    Paint mPaint;
private

2019-03-10 16:43 UTC, tim-teacher commented on app/src/main/java/com/kostikum/itac/dz4/PieChartView.java
> +
пробелы

2019-03-13 19:56 UTC, tim-teacher approved these changes

2019-03-21 22:05 UTC, merged